Refactor person to student
AY2223S1-CS2103T-T09-4/tp pull request #226
Opened 2022-10-28 13:41 UTC by gnahzeus

Improves code quality by refactoring person to student in 
- Class names ✅ 
- method names ✅
- json files ✅
- puml files ✅
- docs ✅
- PERSON constants are not changed. ❌ 

Also fixes style/spelling errors from v1.3 closing.

Addresses #216

2022-10-28 14:02 UTC, Echomo-Xinyu requested changes
Thanks for taking up this tedious work! I have checked your branch and it seems that there are still a few more `Person`s present in the repository. I shall not list down further as you can do a `control+shift+F` to do a global search in the project to catch the missed ones.

2022-10-28 14:03 UTC, Echomo-Xinyu commented
Also, remember to export the PlantUML diagrams to png files to the correct folder after you have modified the puml file! It seems like no png has been updated in this PR yet.

2022-10-29 03:00 UTC, gnahzeus commented on src/main/java/seedu/address/logic/parser/EditCommandParser.java
> +        EditStudentDescriptor editPersonDescriptor = new EditStudentDescriptor();
Thanks for the catch!

2022-10-29 03:00 UTC, gnahzeus commented on docs/diagrams/SortBySequenceDiagram.puml
> +participant "persons:UniqueStudentList" as UniqueStudentList MODEL_COLOR
Good catch! Will do a global search for the rest of persons.

2022-10-29 03:34 UTC, gnahzeus commented
About the PlantUML diagrams to png files, I noticed that there are some other errors (related to AddressBook not changed to Teacher's Pet). I think it is better to address this in another PR that is dedicated to updating the png and puml files for both Person -> Student and AddressBook -> Teacher's Pet. 

@Echomo-Xinyu What are your opinions on this?

2022-10-29 03:42 UTC, seanflyyy commented
@gnahzeus what kind of errors did you notice? is it just pertaining to updating from address book to teacher's pet?

2022-10-29 07:20 UTC, gnahzeus commented
Yes @seanflyyy, the puml and png files are not updated for Teacher's Pet as well.

2022-10-29 07:53 UTC, seanflyyy commented
@gnahzeus sure,in which case let's just modify it in another PR. i'll take it up

2022-10-29 14:15 UTC, seanflyyy approved these changes
LGTM

2022-10-29 14:21 UTC, Echomo-Xinyu approved these changes
LGTM! remember to refactor the remaining two in the future PR!

2022-10-29 14:22 UTC, merged